#!/usr/bin/env bash


## Install ansible
sudo apt-get update -y
sudo apt-get install -y software-properties-common ansible


## Run local.yml
ansible-pull -U https://github.com/tdk141/debian12-ansible.git
