#!/usr/bin/env bash


## Install ansible
sudo apt update -y
sudo apt install -y git software-properties-common ansible


## Run local.yml
ansible-pull -U https://github.com/skraio/debian12-ansible.git
