- name: Install system packages 1
  become: true
  apt:
    name: ["build-essential", "htop", "cmake", "xcape", "xclip", "man"]
  tags:
    - core
    - main_tools

- name: Install system packages 2
  become: true
  apt:
    name: ["unzip", "curl", "git", "python3.11-venv"]
  tags:
    - core
    - main_tools

- name: Install system packages 3
  become: true
  apt:
    name: ["exa", "gettext", "ripgrep"]
  tags:
    - core
    - main_tools
