- name: Installing stow
  become: true
  apt: name=stow
  tags:
    - dotfiles
    - install

- name: Cloning dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/{{user_name}}/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - dotfiles
    - install

- name: Stow dotfiles
  shell: $HOME/dotfiles/scripts/stow_dotfiles.sh
  tags:
    - dotfiles
    - install
