- name: Add Spotify GPG key
  apt_key:
    url: https://download.spotify.com/debian/pubkey_7A3A762FAFD4A51F.gpg
    state: present
  tags:
    - spotify
    - install

- name: Add Spotify repository
  apt_repository:
    repo: "deb http://repository.spotify.com stable non-free"
    state: present
  tags:
    - spotify
    - install

- name: Update APT package cache
  apt:
    update_cache: yes
  tags:
    - spotify
    - install

- name: Install Spotify
  apt:
    name: spotify-client
    state: present
  tags:
    - spotify
    - install
