- name: Install VS Code dependencies
  become: true
  apt:
    name: ["apt-transport-https", "gpg"]
    state: present
    update_cache: true
  tags:
    - vscode
    - install

- name: Add Microsoft signing key
  become: true
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  tags:
    - vscode
    - install

- name: Add Microsoft repository
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present
    filename: vscode
  tags:
    - vscode
    - install

- name: Install VS Code
  become: true
  package:
    name: code
    state: present
  tags:
    - vscode
    - install

- name: Install VS Code Extensions
  become: no
  shell: code --install-extension {{ item | quote }}
  loop:
    - asvetliakov.vscode-neovim
    - mechatroner.rainbow-csv
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.vscode-jupyter-cell-tags
    - ms-toolsai.vscode-jupyter-slideshow
    - ryuta46.multi-command
  tags:
    - vscode
    - ex
    - install
