- name: Install Zsh
  become: true
  apt: name=zsh
  tags:
    - zsh
    - install
    - basis

- name: Change shell to Zsh
  become: no
  shell: chsh -s $(which zsh)
  tags:
    - zsh
    - install
    - basis

- name: Install Oh-My-Zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags:
    - zsh
    - install
    - basis
